name: Setup host environment

on:
  workflow_call:

jobs:
  server_environment:
    name: Setup host environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Create project directory and .env-file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo mkdir -p ${{ secrets.PROJECT_NAME }} -m 777
            sudo cat > ${{ secrets.PROJECT_NAME }}/.env << _EOF_
              SECRET_KEY=${{ secrets.SECRET_KEY }}
              DEBUG=${{ secrets.DEBUG }}
              DOMAIN=${{ secrets.DOMAIN }}
              EMAIL=${{ secrets.EMAIL }}

              DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
              DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
              DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}

              DB_ENGINE=${{ secrets.DB_ENGINE }}
              DB_NAME=${{ secrets.DB_NAME }}
              POSTGRES_USER=${{ secrets.POSTGRES_USER }}
              POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
              DB_HOST=${{ secrets.DB_HOST }}
              DB_PORT=${{ secrets.DB_PORT }}

              PROJECT_NAME=${{ secrets.PROJECT_NAME }}
              DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            _EOF_
      - name: copy infra files via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "infra/server/docker-compose.yml, infra/server/nginx.conf"
          target: ${{ secrets.PROJECT_NAME }}
          overwrite: true
          strip_components: 2
